-- MySQL Script generated by MySQL Workbench
-- Thu Aug 30 22:54:57 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cultivar` DEFAULT CHARACTER SET utf8 ;
USE `cultivar` ;

-- -----------------------------------------------------
-- Table `address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `address` (
  `cod_address` INT NOT NULL AUTO_INCREMENT,
  `nm_city` VARCHAR(45) NOT NULL,
  `nm_neighborhood` VARCHAR(45) NOT NULL,
  `nm_street` VARCHAR(45) NOT NULL,
  `nu_street` VARCHAR(45) NULL DEFAULT 'S/N',
  PRIMARY KEY (`cod_address`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `users` (
  `dt_create` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `cod_cpf` VARCHAR(11) NOT NULL,
  `nm_user` VARCHAR(225) NOT NULL,
  `dsc_email` VARCHAR(225) NOT NULL,
  `dsc_password` VARCHAR(45) NOT NULL,
  `dsc_role` ENUM('VOLUNTEER', 'ADMIN', 'COMPANY_ADMIN', 'SCHOOL_ADMIN') NULL DEFAULT 'VOLUNTEER',
  `sta_user` ENUM('APPROVED', 'WAIT_STATEMENT', 'WAIT_COMPANY', 'WAIT_TRAINING', 'REGISTER') NULL DEFAULT 'REGISTER',
  `dt_birth` DATE NOT NULL,
  `dsc_job` VARCHAR(225) NOT NULL,
  `dsc_phone` VARCHAR(11) NOT NULL,
  `cod_address` INT NOT NULL,
  PRIMARY KEY (`cod_cpf`),
  INDEX `fk_users_address1_idx` (`cod_address` ASC),
  CONSTRAINT `fk_users_address1`
    FOREIGN KEY (`cod_address`)
    REFERENCES `address` (`cod_address`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `question`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `question` (
  `cod_question` INT NOT NULL AUTO_INCREMENT,
  `dsc_question` TEXT NOT NULL,
  PRIMARY KEY (`cod_question`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `company`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `company` (
  `cod_cnpj` VARCHAR(14) NOT NULL,
  `nm_company` VARCHAR(225) NOT NULL,
  `cod_address` INT NOT NULL,
  `cod_cpf` VARCHAR(11) NOT NULL,
  `dsc_phone` VARCHAR(11) NOT NULL,
  INDEX `fk_company_address1_idx` (`cod_address` ASC),
  PRIMARY KEY (`cod_cnpj`),
  INDEX `fk_company_users1_idx` (`cod_cpf` ASC),
  CONSTRAINT `fk_company_address1`
    FOREIGN KEY (`cod_address`)
    REFERENCES `address` (`cod_address`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_company_users1`
    FOREIGN KEY (`cod_cpf`)
    REFERENCES `users` (`cod_cpf`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `volunteer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `volunteer` (
  `cod_cpf` VARCHAR(11) NOT NULL,
  `cod_cnpj` VARCHAR(14) NOT NULL,
  `dsc_schooling` ENUM('ELEMENTARY_SCHOOL', 'HIGH_SCHOOL', 'UNIVERSITY_GRADUATE', 'POSTGRADUATE_STUDIES') NOT NULL,
  `fl_conclusion` TINYINT NOT NULL,
  `cod_rg` VARCHAR(15) NOT NULL,
  `nm_volunteer` VARCHAR(225) NOT NULL,
  PRIMARY KEY (`cod_cpf`, `cod_cnpj`),
  INDEX `fk_volunteer_users1_idx` (`cod_cpf` ASC),
  INDEX `fk_volunteer_company1_idx` (`cod_cnpj` ASC),
  CONSTRAINT `fk_volunteer_users1`
    FOREIGN KEY (`cod_cpf`)
    REFERENCES `users` (`cod_cpf`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_volunteer_company1`
    FOREIGN KEY (`cod_cnpj`)
    REFERENCES `company` (`cod_cnpj`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `answer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `answer` (
  `cod_question` INT NOT NULL,
  `fl_answer` TINYINT NULL DEFAULT 0,
  `dsc_answer` TEXT NULL,
  `cod_cpf` VARCHAR(11) NOT NULL,
  PRIMARY KEY (`cod_question`, `cod_cpf`),
  INDEX `fk_answer_question1_idx` (`cod_question` ASC),
  INDEX `fk_answer_volunteer1_idx` (`cod_cpf` ASC),
  CONSTRAINT `fk_answer_question1`
    FOREIGN KEY (`cod_question`)
    REFERENCES `question` (`cod_question`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_answer_volunteer1`
    FOREIGN KEY (`cod_cpf`)
    REFERENCES `volunteer` (`cod_cpf`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `school`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `school` (
  `cod_school` INT NOT NULL AUTO_INCREMENT,
  `nm_school` VARCHAR(225) NOT NULL,
  `dsc_phone` VARCHAR(11) NOT NULL,
  `cod_address` INT NOT NULL,
  `cod_cpf` VARCHAR(11) NOT NULL,
  PRIMARY KEY (`cod_school`),
  INDEX `fk_school_address1_idx` (`cod_address` ASC),
  INDEX `fk_school_users1_idx` (`cod_cpf` ASC),
  CONSTRAINT `fk_school_address1`
    FOREIGN KEY (`cod_address`)
    REFERENCES `address` (`cod_address`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_school_users1`
    FOREIGN KEY (`cod_cpf`)
    REFERENCES `users` (`cod_cpf`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `attachment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `attachment` (
  `cod_attachment` INT NOT NULL AUTO_INCREMENT,
  `nm_attachment` VARCHAR(225) NOT NULL,
  `fl_required` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`cod_attachment`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dispatch`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dispatch` (
  `fl_dispatch` TINYINT NULL DEFAULT 0,
  `cod_attachment` INT NOT NULL,
  `cod_cpf` VARCHAR(11) NOT NULL,
  PRIMARY KEY (`cod_attachment`, `cod_cpf`),
  INDEX `fk_dispatch_attachment1_idx` (`cod_attachment` ASC),
  INDEX `fk_dispatch_volunteer1_idx` (`cod_cpf` ASC),
  CONSTRAINT `fk_dispatch_attachment1`
    FOREIGN KEY (`cod_attachment`)
    REFERENCES `attachment` (`cod_attachment`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_dispatch_volunteer1`
    FOREIGN KEY (`cod_cpf`)
    REFERENCES `volunteer` (`cod_cpf`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `event`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `event` (
  `cod_event` INT NOT NULL AUTO_INCREMENT,
  `dt_start_occurrence` DATETIME NOT NULL,
  `dt_create` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `tp_event` ENUM('TRAINING', 'TUTORING', 'MEETING') NOT NULL,
  `cod_address` INT NOT NULL,
  `dt_end_occurrence` DATETIME NOT NULL,
  `fl_all_day` TINYINT NULL DEFAULT 0,
  PRIMARY KEY (`cod_event`),
  INDEX `fk_event_address1_idx` (`cod_address` ASC),
  CONSTRAINT `fk_event_address1`
    FOREIGN KEY (`cod_address`)
    REFERENCES `address` (`cod_address`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `participation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `participation` (
  `cod_event` INT NOT NULL,
  `cod_cpf` VARCHAR(11) NOT NULL,
  INDEX `fk_participation_event1_idx` (`cod_event` ASC),
  PRIMARY KEY (`cod_event`, `cod_cpf`),
  INDEX `fk_participation_users1_idx` (`cod_cpf` ASC),
  CONSTRAINT `fk_participation_event1`
    FOREIGN KEY (`cod_event`)
    REFERENCES `event` (`cod_event`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_participation_users1`
    FOREIGN KEY (`cod_cpf`)
    REFERENCES `users` (`cod_cpf`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `training`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `training` (
  `cod_training` INT NOT NULL AUTO_INCREMENT,
  `nm_training` VARCHAR(225) NOT NULL,
  `dsc_path` VARCHAR(225) NULL,
  `dsc_link` VARCHAR(225) NULL,
  `cod_event` INT NOT NULL,
  PRIMARY KEY (`cod_training`),
  INDEX `fk_trainning_event1_idx` (`cod_event` ASC),
  CONSTRAINT `fk_trainning_event1`
    FOREIGN KEY (`cod_event`)
    REFERENCES `event` (`cod_event`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rating`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rating` (
  `vl_rating` INT NOT NULL,
  `dsc_rating` TEXT NULL,
  `cod_cpf` VARCHAR(11) NULL,
  `cod_event` INT NULL,
  INDEX `fk_rating_users1_idx` (`cod_cpf` ASC),
  INDEX `fk_rating_event1_idx` (`cod_event` ASC),
  CONSTRAINT `fk_rating_users1`
    FOREIGN KEY (`cod_cpf`)
    REFERENCES `users` (`cod_cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_rating_event1`
    FOREIGN KEY (`cod_event`)
    REFERENCES `event` (`cod_event`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
