export default {
    'Florianópolis': [
        'Abraão',
        'Agronômica',
        'Balneário',
        'Balneário Daniela',
        'Barra da Lagoa',
        'Bom Abrigo',
        'Cachoeira do Bom Jesus',
        'Cacupé',
        'Campeche',
        'Canasvieiras',
        'Capoeiras',
        'Carianos',
        'Carvoeira',
        'Centro',
        'Coloninha',
        'Coqueiros',
        'Córrego Grande',
        'Costa de Dentro',
        'Costeira do Pirajubaé',
        'Estreito',
        'Ingleses do Rio Vermelho',
        'Itacorubi',
        'Itaguaçu',
        'Jardim Atlântico',
        'José Mendes (Florianópolis)',
        'João Paulo',
        'Jurerê',
        'Lagoa da Conceição',
        'Monte Verde',
        'Morro das Pedras',
        'Pantanal',
        'Prainha',
        'Pântano do Sul',
        'Ponta das Canas',
        'Ratones',
        'Ribeirão da Ilha',
        'Rio Tavares',
        'Rio Vermelho',
        'Saco dos Limões',
        'Saco Grande',
        'Santa Mônica',
        'Santo Antônio de Lisboa',
        'Trindade',
        'Vargem do Bom Jesus',
        'Vargem Grande',
        'Vargem Pequena'
    ],
    'Palhoça': [
        'Albardão',
        'Alto Aririu',
        'Aririu',
        'Aririu Formiga',
        'Balneário Ponta Papagaio',
        'Barra Aririu',
        'Barra do Aririu',
        'Bela Vista',
        'Brejaru',
        'Caminho Novo',
        'Centro',
        'Cidade Universitária Pedra Branca',
        'Enseada do Brito',
        'Guarda do Cubatão',
        'Guarda Embau',
        'Jardim Aquarius',
        'Jardim Carioca',
        'Jardim Coqueiros',
        'Jardim das Palmeiras',
        'Jardim Eldorado',
        'Maciambu',
        'Nova Palhoça',
        'Pacheco',
        'Pachecos',
        'Passa Vinte',
        'Passagem de Maciambu',
        'Pedra Branca',
        'Pinheira',
        'Pintora Papagaio',
        'Ponte Imaruim',
        'Praia Fora',
        'Praia Meio',
        'Praia Pinheira',
        'Praia Sonho',
        'Rio Grande',
        'São Sebastião',
        'Terra Fraca'
    ],
    'São José': [
        'Centro',
        'Ponta de Baixo',
        'Fazenda Santo Antônio',
        'Distrito Industrial',
        'Picadas do Sul',
        'Flor de Nápolis',
        'Forquilhinhas',
        'Praia Comprida',
        'São Luiz',
        'Roçado',
        'Bosque das Mansões',
        'Potecas',
        'Forquilhas',
        'Sertão do Maruim',
        'Colônia Santana',
        'Barreiros',
        'Nossa Senhora do Rosário',
        'Bela Vista',
        'Jardim Cidade de Florianópolis',
        'Ipiranga',
        'Pedregal',
        'Jardim Santiago',
        'Areias',
        'Serraria',
        'Real Parque',
        'Campinas',
        'Kobrasol'
    ]
}